#!/bin/bash
temp=$(xclip -o 1>&2 &)
echo -n | xclip
SECRETSPATH="/<FULLPATH>/"
SECRETFILE=`ls $SECRETSPATH | dmenu`
[ ! -f "${SECRETSPATH}${SECRETFILE}" ] && echo "gpg encrypted secret file does not exist: ${SECRETSPATH}${SECRETFILE}" 1>&2 && exit 1
SECRET=$(gpg -q --decrypt "${SECRETSPATH}${SECRETFILE}")
[ $? != "0" ] && echo "gpg decrypt error" 1>&2 && exit 1
pkill -f "^totpsleep" 2>/dev/null && sleep 0.5
oathtool --base32 --totp "$SECRET" | xclip -i
if [[ -t 1 ]]; then
xclip -o -selection -clipboard 
else
xclip -o -selection -clipboard | xdotool type --clearmodifiers --file - 
fi
(
( exec -a "totpsleep" sleep 45 )
echo -n $temp | xclip
) 2>/dev/null & disown
